language: node_js

node_js:
  - 6

services:
  - docker

install: true

script:
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/frontend-test/web .
  - docker push registry.heroku.com/frontend-test/web
